### ISSUE TITLE
IRB File Documentation

### ISSUE THREAD

**Issue by annalen** [gadomski/irb-rs#1]
Hallo,

Is there a documentation about the irb. file format by infratec?

Many Thanks

**Comment by gadomski** [comment]
I have documentation for their SDK, but not for the format itself, sorry.

**Comment by annalen** [comment]
Hallo @gadomski,

I would like to read these irb. file with a programming language and do some analysis tasks (for example edge detection).
Is it possible to process these irb. files with a programming language (eg. python or matlab)? Do you have experience with these task?

Many Thanks.

**Comment by gadomski** [comment]
The Infratec IRBSDK only exposes C headers, so to use the SDK in another programming language you'll have to create a wrapper, which is what [irbacs-sys](https://github.com/gadomski/irb-rs/tree/master/irbacs-sys) does. Here's some [Python documentation on the topic](https://docs.python.org/3.7/extending/extending.html) and [for Matlab](https://www.mathworks.com/solutions/matlab-and-c.html). Hope that helps!

**Comment by annalen** [comment]
Hallo @gadomski,

I speed much time in struggling with the intregation of the infratec sdk in python.

Here is my code snippet for loading the dll file and calling the loadIRB file:

 ```
# import ctypes lib
import ctypes
from ctypes import *

# load 64-bit dll
mydll = cdll.LoadLibrary("C:/Program Files (x86)/InfraTec/IRBACS_SDK/v2/Win64/irbacs_w64.dll")

# define function loadIRB
funcObj = mydll.loadIRB
funcObj.restype = ctypes.c_void_p
funcObj.argtypes = [ctypes.c_char_p]

# calling function loadiRB with path to the image
fn = ctypes.c_char_p("image.irb".encode('utf-8'))
ret = funcObj(fn)
print(ret)
```

But the ret object is always None. 
Do you know what I'm doing wrong?


Many Thanks.
